### ISSUE TITLE
Add tutorials to github wiki

### ISSUE THREAD

**Issue by bill-wright** [aphysci/gravity#1]
Should get the tutorials checked out and uploaded.

**Comment by jmangelson** [comment]
Are there tutorials for how to do playback of archives?

I am trying to playback an existing archive, but I can't find documentation on how to do so.

**Comment by cbrundick** [comment]
We're still working on the tutorials. In the Gravity bin directory you'll find a FileArchiver executable that can be used to replay archive files. It operates as a standard Gravity component, publishing data products from the archive. You can specify the archive file to be replayed using the 'ArchiveFilename' parameter in the INI file. In addition, you can optionally specify a subset of the data products to replay by providing a comma separated list of data product IDs using the 'DataProductList' parameter. A sample INI file follows:

[general]
ServiceDirectoryURL="tcp://localhost:5555"
ArchiveFilename="archive.bin"
DataProductList="ShipMotionData"

We also have a Java archive reader (and writer) with a more useful user interface that should be added to the Gravity open source soon...

Chris

**Comment by mbarger99** [comment]
Wiki pages for basic Gravity setup and a walk-through of the examples have been added.
