### ISSUE TITLE
Question: What is best way to handle many-to-one messages?

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#10]
Imagine an alert data product, where many nodes can publish this data product and a single node subscribes to this alert data product.  It seems that a node can only publish() data if you have called registerDataProduct(), and this makes it so only one node can publish data.  And I don't want the single node to have to know all the possible nodes that can possibly connect and send alerts.

The only workaround I can see is to use the GravityRequestor interface, and send these alert type messages as request() .  Do you all agree, and is this the best way to do something like this?

**Comment by CptanPanic** [comment]
Ok,
I was playing around with 2-ProtobufDataProduct example, and did verify that starting up 2 ./ProtobufDataProductPublisher, the subscriber does receive both messages.  

Can you explain how this works? I was under the impression a zeromq pub/sub socket would only work in the one to many direction and not the other way around.

**Comment by cbrundick** [comment]
When a publisher registers with the service directory, it's essentially added to a list of publishers maintained by the service directory and associated with a specific data product. When a subscriber subscribes to that data product, a zmq pub/sub connection is established between the subscriber and each registered publisher. So, if there are multiple publishers, the subscriber will have a separate connection to each one. The GravityNode aggregates the incoming messages from all those connections and provides them through the subscriptionFilled() call.
