### ISSUE TITLE
Java compile fails on GravityHeartbeatListener.h

### ISSUE THREAD

**Issue by DaveParillo** [aphysci/gravity#106]
Doxygen changes also added a few GRAVITY_API to src/api/cpp/GravityHeartbeatListener.h, but it doesn't include Utility.h, so the compile fails because the cpp compiler is trying to interpret GRAVITY_API as a return type.

If we are  going to kepp GRAVITY_API in GravityHeartbeatListener.h, then need to add `#include "Utility.h"`

**Comment by DaveParillo** [comment]
PR #107  closes this issue.

**Comment by mbarger99** [comment]
Forgot to close this - fixed in #107.
