### ISSUE TITLE
Intermittent SIGSEGV shutting down

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#13]
This may be another case that you cannot really recreate, but I get a SIGSEGV with my unit tests sometimes when test is complete.  I don't see anyway to shutdown Subscription Manager, but have you seen this before?  

```
#0  0x00007ffff7874735 in gravity::Log::vLog (level=16, format=0x7ffff78c91b0 "Interrupted, exiting (rc = %d)", args=0x7ffff3db6928) at GravityLogger.cpp:301
#1  0x00007ffff7874c53 in gravity::Log::debug (message=0x7ffff78c91b0 "Interrupted, exiting (rc = %d)") at GravityLogger.cpp:412
#2  0x00007ffff788cff3 in gravity::GravitySubscriptionManager::start (this=0x7ffff3db6d50) at GravitySubscriptionManager.cpp:101
#3  0x00007ffff7875dbe in startSubscriptionManager (context=0x7792e0) at GravityNode.cpp:76
#4  0x00007ffff6cbbe25 in start_thread () from /lib64/libpthread.so.0
#5  0x00007ffff574a34d in clone () from /lib64/libc.so.6
```

**Comment by mbarger99** [comment]
Are you using a custom Logger, or just the Loggers that are automatically started by GravityNode (FileLogger and ConsoleLogger)?

When the GravitySubscriptionManager sees that the zmq connection to the GravityNode fails/closes, it assumes that it should shutdown.  At that point it breaks out of the main loop and cleans up its resources before terminating.  That "interrupted ..." message in the stack trace shows that it just detected that zmq socket disconnect.

**Comment by CptanPanic** [comment]
Turns out I may have had a case where the gravity node was being started twice, but deleted once.  I would say this is too convoluted a case for anyone else to encounter.
