### ISSUE TITLE
swig/python detected a memory leak of type 'int64_t *', no destructor found.

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#15]
I am trying out the python interface for listening to heartbeats, and I get this error when I miss a heartbeat.  Is there something wrong with my python declaration or with the code itself? 

Thanks,

`swig/python detected a memory leak of type 'int64_t *', no destructor found.
`

```
class MyListener(GravityHeartbeatListener):
    def __init__(self):
        super(MyListener, self).__init__()

    def MissedHeartbeat(self, componentId, microsecond_to_last_heartbeat, interval_in_microseconds):
        print("missed heartbeat")

    def ReceivedHeartbeat(self, componentID, interval_in_microseconds):
        print("received heartbeat")

```

**Comment by mbarger99** [comment]
Hi @CptanPanic,

Your listener class looks good to me.  Are you able to run the python test included with the distribution in test/api/python?  Your class looks basically the same as the TestHBListener class in that test code, but I'm not seeing any issues when I run that.  Do you get a similar error with that?

**Comment by CptanPanic** [comment]
Yes I get the same error below.  Note I am using SWIG 3.0.12, and python 2.7.5.

```
rm -rf ./PythonTestPB.py
Building  PythonTestPB.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: PythonTestPB.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
/usr/bin/python pytest.py
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
[02/27/18 10:56:31.007273 PythonTest-CRITICAL] Heartbeat Message Error: Context was terminated
```

**Comment by mbarger99** [comment]
Thanks, the version info was going to be my next question.  I've tested this with Python 2.7.12/swig 3.0.8 and Python 2.7.6/swig 2.0.11, but I'm not seeing that warning with either.  My guess is that this is related to the newer swig you have, and that it may not be generating the destructor for the C++ wrapper in the same way that it is in the versions I've used.  It's strange that you're only seeing this on the missed heartbeats though.

I see that you're also running with a newer version of the protobuf library - we're still using 2.6.1, before they added proto3 support.  But if it were related to this, I would think you would be seeing this warning many more times given how much of the code references these.

I also notice that you're using the latest swig, but an older Python.  Not sure that it matters, but I wonder if that combination could have issues.

I'll try getting the latest swig and see if I can replicate what you're seeing.  It may be a couple days before I can get to that though.

**Comment by CptanPanic** [comment]
Note I originally had SWIG 2.0.10 but I was getting a error building on gravitynode.i .

**Comment by mbarger99** [comment]
Good to know, thanks.

**Comment by mbarger99** [comment]
OK, so looks like swig changed the way they handle int64_t in the latest version.  In older versions we didn't need any special handling for int64_t.  In the latest version though, if you don't include any additional typemaps or casts they allocate memory to wrap an int64_t that they don't delete.  Fortunately, they provide everything we need in the stdint.i file, which is also available in older versions.  I test this with swig 2.0.11, and it worked there as well.

Fixed in https://github.com/aphysci/gravity/releases/tag/v1.11.1.

**Comment by pchao6** [comment]
Update TensorFlow to at least 1.4.

**Comment by lijunwei19** [comment]
> Yes I get the same error below. Note I am using SWIG 3.0.12, and python 2.7.5.
> 
> ```
> rm -rf ./PythonTestPB.py
> Building  PythonTestPB.proto
> [libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: PythonTestPB.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
> /usr/bin/python pytest.py
> swig/python detected a memory leak of type 'int64_t *', no destructor found.
> swig/python detected a memory leak of type 'int64_t *', no destructor found.
> swig/python detected a memory leak of type 'int64_t *', no destructor found.
> swig/python detected a memory leak of type 'int64_t *', no destructor found.
> swig/python detected a memory leak of type 'int64_t *', no destructor found.
> [02/27/18 10:56:31.007273 PythonTest-CRITICAL] Heartbeat Message Error: Context was terminated
> ```

I got a similar problem, my version also : 
AttributeError: 'SwigPyObject' object has no attribute 'set_string'
swig/python detected a memory leak of type 'Config *', no destructor found.
pi@raspberrypi:~$ swig --version
SWIG Version 3.0.12

Compiled with g++ [armv8l-unknown-linux-gnueabihf]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

how do you solve that problem?  thank you.

**Comment by mbarger99** [comment]
To make sure I understand, you're seeing the int64_t warnings when you run the gravity tests?  And you're also seeing a similar warning from your own code?  I don't know what the Config class is, so I'm not sure why swig would be trying to build a wrapper for it.

As for the gravity warnings, what version of gravity are you using?
