### ISSUE TITLE
INI file parser causes segfault on unterminated quoted strings

### ISSUE THREAD

**Issue by bill-wright** [aphysci/gravity#160]
A line like this in Gravity.ini (notice the missing close-quote):

`config_file = "./config/cc.json`

causes all GravityNodes to crash with a segfault.  Would be better to report the parse error.

**Comment by JBBee** [comment]
I suggest we take a poll to see if people are actually using the INI file parser's variable substitution capabilities in INI files.  If we find usage is limited perhaps we can re-write this library to make it more simple and not depend on flex and bison, and we could even just include it in gravity as a single class so we can remove a library.  I say this because I don't believe I'm stepping on anyone's toes here as I believe I wrote this whole library.  If someone else contributed to it and I don't recall than I apologize and we can table this.

**Comment by mbarger99** [comment]
I'm pretty sure I've never used those features, so I'd be OK with removing them.  Having said that, I don't think this implementation has caused that many issues.  If we remove it, we'd need to put something else in its place, which could lead to issues of its own.  The main benefit I think would be a simplified build, but if we use a third party library for this support, we would just be adding a new dependency in its place.  So I'm inclined to leave this implementation as is (aside from fixing this particular issue), but it's not a strong preference.

**Comment by cbrundick** [comment]
I do think we've encountered a few issues with the parser over the years. Nothing significant. In the short-term I'm fine with fixing this issue, but  I think my inclination would be to look into 3rd party options.

**Comment by JBBee** [comment]
Ok, I'll take this issue.  I did find a simple 3rd party option with a compatible license that looks pretty good I'll send to you.

**Comment by mbarger99** [comment]
Sounds like there have been more issues with the parser than I remembered.  So yeah, I'm good with looking at other options.

**Comment by JBBee** [comment]
@bill-wright I tested an unterminated quoted string in a Gravity.ini and it reported the error with the line number.  Hmm, are you able to send the ini file you experienced the crash with?  Thanks.

**Comment by bill-wright** [comment]
I'm having trouble reproducing it with the latest build, too.  Here's the file that causes the ServiceDirectory to dump core:

[Gravity.ini.txt](https://github.com/aphysci/gravity/files/5126083/Gravity.ini.txt)

when built from commit 3cd7077448d514af4d94e627d97daa09a33836e4 on Ubuntu 18.04.4, GCC 7.5.0.

Not sure how much effort this is worth.

**Comment by mbarger99** [comment]
Seems like @JBBee's fix addressed the underlying issue.  Going to go ahead and close this, can reopen if needed.
