### ISSUE TITLE
GravityNode::getComponentID is declared, but never defined.

### ISSUE THREAD

**Issue by Tsubashi** [aphysci/gravity#2]
As the title suggests, GravityNode::getComponentID is declared in [GravityNode.h](https://github.com/aphysci/gravity/blob/master/src/api/cpp/GravityNode.h#L336) but is never defined in [GravityNode.cpp](https://github.com/aphysci/gravity/blob/master/src/api/cpp/GravityNode.cpp)

**Comment by mbarger99** [comment]
Good catch Tsubashi, thanks for submitting this.  This method (obviously) isn't covered in the tests, and apparently isn't a feature that anyone has used yet, so it was never noticed.  I'll add this to the swig interface and add test code in C++ and Java.
