### ISSUE TITLE
Examples require -lsodium on Ubuntu 16.04

### ISSUE THREAD

**Issue by chrismurf** [aphysci/gravity#20]
Compilation of examples fails under Ubuntu 16.04 when using libraries straight from the ubuntu repository.  The distributed version of zeromq requires linking explicitly against libsodium (perhaps that was previously built with zeromq?)

> make[1]: Entering directory '/home/chrismurf/lib/gravity/test/examples/1-BasicDataProduct'
> g++ -o BasicDataProductPublisher BasicDataProductPublisher.cpp -I../../../src/api/cpp/ -I/usr/local/include -I/usr/include -Wall -L../../../src/api/cpp/ -L../../../src/keyvalue_parser/ -L/usr/local/lib -L/usr/local/lib -g -O2 -Wl,-Bstatic -lgravity -lkeyvalue_parser -lprotobuf -lzmq -Wl,-Bdynamic -lrt -lpthread
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-ctx.o): In function `zmq::ctx_t::~ctx_t()':
> (.text+0xfa6): undefined reference to `randombytes_close'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-zmq_utils.o): In function `zmq_curve_keypair':
> (.text+0x337): undefined reference to `crypto_box_keypair'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::encode(zmq::msg_t*)':
> (.text+0x176): undefined reference to `crypto_box_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::decode(zmq::msg_t*)':
> (.text+0x4ab): undefined reference to `crypto_box_open_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::curve_client_t(zmq::options_t const&)':
> (.text+0x87e): undefined reference to `sodium_init'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::curve_client_t(zmq::options_t const&)':
> (.text+0x89a): undefined reference to `crypto_box_keypair'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_hello(zmq::msg_t*)':
> (.text+0xb9a): undefined reference to `crypto_box'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_welcome(unsigned char const*, unsigned long)':
> (.text+0xe25): undefined reference to `crypto_box_open'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_welcome(unsigned char const*, unsigned long)':
> (.text+0xf17): undefined reference to `crypto_box_beforenm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
> (.text+0x108a): undefined reference to `randombytes'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
> (.text+0x10ae): undefined reference to `crypto_box'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
> (.text+0x12b3): undefined reference to `crypto_box'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_ready(unsigned char const*, unsigned long)':
> (.text+0x15e0): undefined reference to `crypto_box_open_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::encode(zmq::msg_t*)':
> (.text+0x176): undefined reference to `crypto_box_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::decode(zmq::msg_t*)':
> (.text+0x5bb): undefined reference to `crypto_box_open_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::curve_server_t(zmq::session_base_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zmq::options_t const&)':
> (.text+0x959): undefined reference to `sodium_init'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::curve_server_t(zmq::session_base_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zmq::options_t const&)':
> (.text+0x975): undefined reference to `crypto_box_keypair'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_hello(zmq::msg_t*)':
> (.text+0xdc6): undefined reference to `crypto_box_open'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
> (.text+0xeed): undefined reference to `randombytes'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
> (.text+0xf81): undefined reference to `randombytes'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
> (.text+0xf9e): undefined reference to `crypto_secretbox'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
> (.text+0xfc4): undefined reference to `randombytes'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
> (.text+0x10fb): undefined reference to `crypto_box'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_ready(zmq::msg_t*)':
> (.text+0x13b1): undefined reference to `crypto_box_afternm'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
> (.text+0x231e): undefined reference to `crypto_secretbox_open'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
> (.text+0x2400): undefined reference to `crypto_box_open'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
> (.text+0x2513): undefined reference to `crypto_box_open'
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
> (.text+0x254a): undefined reference to `crypto_box_beforenm'
> collect2: error: ld returned 1 exit status
> Makefile:81: recipe for target 'BasicDataProductPublisher' failed
> make[1]: *** [BasicDataProductPublisher] Error 1
> make[1]: Leaving directory '/home/chrismurf/lib/gravity/test/examples/1-BasicDataProduct'
> Makefile:50: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by chrismurf** [comment]
This can be fixed by appending "-lsodium" to the Linux-specific OS_SPECIFIC_LIBS line as follows:
> OS_SPECIFIC_LIBS = -lzmq -Wl,-Bdynamic -lrt -lpthread -lsodium

With this change to Makefile.in for examples [1,2,3,4,5,8,9,10,13], the examples compile and can be run successfully under Ubuntu 16.04 out of the box.

As Makefile.in is currently crafted, I'm not sure how best to do this based on Ubuntu versions - the current switch is only Linux vs. non-Linux.

**Comment by mbarger99** [comment]
Thanks for opening this and for the additional info.  We need to make a few updates to the build file templates, so we'll try to work in something to make this easier then.  

At some point we also need to test against newer versions of the zmq and protobuf libraries to make sure we're compatible, but that may not happen soon.
