### ISSUE TITLE
Python binding segfaults when GravitySubscriber goes out of scope

### ISSUE THREAD

**Issue by chrismurf** [aphysci/gravity#22]
If you subscribe using a GravitySubscriber object in a scope that later disappears, the python environment will segfault.

I suspect that the GravitySubscriber's reference count is not being appropriately incremented in GravityNode::subscribe(), but I'm not familiar enough with SWIG to fix it quickly.

This will cause a segfault:

```python
#!/usr/bin/env python

import gravity

class MySubscriber(gravity.GravitySubscriber):
  def subscriptionFilled(self, dataProducts):
    print "Success."

def subscribe_in_disappearing_scope(node):
  subscriber = MySubscriber()
  node.subscribe("SomePublicationThatExists", subscriber)


node = gravity.GravityNode()
node.init("IAmGonnaSegfault")
subscribe_in_disappearing_scope(node)
node.waitForExit()
```

**Comment by chrismurf** [comment]
What if we use a std::tr1::function as a callback instead?

**Comment by mbarger99** [comment]
As currently implemented, it's the callers responsibility to unsubscribe before the subscriber object is destroyed.  There's no consistent way to verify that the reference held to the subscriber is still valid, so we have to rely on the caller to perform that cleanup.

We can look at changing this in future versions (maybe by changing to a weak_ptr, or using a std::tr1::function as you suggest), but that would be a pretty significant API change that would break a lot of existing code.  But we'll keep this mind when we look at other API breaking changes.

**Comment by chrismurf** [comment]
Disagree - there is absolutely a consistent way.  It is the Python binding's responsibility to increment the reference count on the Python callback wrapper when subscribe() is called.  That will prevent Python from garbage collecting the Python object, and thus destroying the c++ callback.

Any issue that causes a Python segfault is a major bug - Python should never segfault.

**Comment by mbarger99** [comment]
That's true, we could work around this in the Python binding, but the fundamental limitation is still there in the C++ API.  When I said there's no consistent way, I was referring to validating the reference held in the underlying C++.

It is reasonable though, that if we can improve this for a particular implementation without overhauling the existing API we should do it.  Reopening...

**Comment by chrismurf** [comment]
I think this fixes it, but I'm not 100% given my lack of SWIG experience.  Looking at sys.getrefcount() from within python makes it seem like the right thing is happening, even when I subscribe and unsubscribe.

[Patch](https://gist.github.com/chrismurf/e7c65d0728ec19de17fd6ff59ac1f64d)

**Comment by mbarger99** [comment]
I spent some time with the patch and it does seem to workaround the issue with no other impact.  Just committed it.
