### ISSUE TITLE
When using ConfigServer, items are not set to lower case.

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#4]
In ParseConfigFile() it calls StringCopyToLowerCase() for all the items, but when using ConfigServer, ParseConfigService() doesn't make it lower case. This makes it different for node when switching from server/local config file.

**Comment by mbarger99** [comment]
Good Catch Cptan.  This really needs to be consistent with the local config files.

**Comment by mbarger99** [comment]
I wanted to note here that I fixed a couple of related issues in this update as well:
 * ConfigServer values now have lower precedence than local config values. 
 * I added the ConfigServer to the ConfigFile example (number 8)
