### ISSUE TITLE
Bad delete in a few files

### ISSUE THREAD

**Issue by DaveParillo** [aphysci/gravity#60]
Code in GravityNode.cpp and FutureResponse.cpp allocate free store arrays, but deallocate using ``delete`` vice ``delete[]``.

See https://github.com/aphysci/gravity/blob/746afaabcdd73a22154a88e2aeae92f72c527284/src/api/cpp/GravityNode.cpp#L2248

https://github.com/aphysci/gravity/blob/746afaabcdd73a22154a88e2aeae92f72c527284/src/api/cpp/FutureResponse.cpp#L54

**Comment by cbrundick** [comment]
Good catch. I'll fix these.

**Comment by cbrundick** [comment]
Fixed in v1.12.11
